CREATE TABLE Authors(
    AUTHOR_ID INT IDENTITY(1,1) NOT NULL,
    AUTHOR_NAME VARCHAR(50) NOT NULL,
);

ALTER TABLE Authors
	ADD PRIMARY KEY (AUTHOR_ID);


CREATE TABLE Categories(
    CATEGORY_ID INT IDENTITY(1,1) NOT NULL,
    CATEGORY_NAME VARCHAR(20) NOT NULL
);

ALTER TABLE Categories
	ADD PRIMARY KEY (CATEGORY_ID);


CREATE TABLE Users(
    USER_ID INT IDENTITY(1,1) NOT NULL,
    USER_USERNAME VARCHAR(30),
    USER_PASSWORD VARCHAR(100),
    USER_EMAIL VARCHAR(30),
    USER_NAME VARCHAR(30),
    USER_BIRTHDATE DATE,
    USER_GENDER VARCHAR(10),
    USER_CATEGORY VARCHAR(10),
    USER_PHOTO VARCHAR(150)
);

ALTER TABLE Users
	ADD PRIMARY KEY (USER_ID);

CREATE TABLE Books(
    BOOK_ID INT IDENTITY(1,1) NOT NULL,
    BOOK_TITLE VARCHAR(100),
	BOOK_YEAR VARCHAR(10),
    BOOK_SHELF VARCHAR(10),
	BOOK_DESCRIPTION VARCHAR(200),
    BOOK_PAGECOUNT INT,
    BOOK_STATUS VARCHAR(20),
    BOOK_COUNT INT,
	BOOK_COVERIMAGE VARCHAR(150),
    AUTHOR_ID INT,
    CATEGORY_ID INT,
);

ALTER TABLE Books
	ADD PRIMARY KEY (BOOK_ID);

ALTER TABLE Books
	ADD FOREIGN KEY (AUTHOR_ID) REFERENCES Authors(AUTHOR_ID);

ALTER TABLE Books
	ADD FOREIGN KEY (CATEGORY_ID) REFERENCES Categories(CATEGORY_ID);

CREATE TABLE Borrows(
    BORROW_ID INT IDENTITY(1,1) NOT NULL,
    BOOK_ID INT,
    USER_ID INT,
    BORROW_STARTDATE DATE,
    BORROW_EXPECTEDRETURNDATE DATE,
    BORROW_RETURNDATE DATE,
	BORROW_STATUS VARCHAR(15),
    CONSTRAINT FK1_BORROW FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID),
    CONSTRAINT FK2_BORROW FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

ALTER TABLE Borrows
	ADD PRIMARY KEY (BORROW_ID);

ALTER TABLE Borrows
	ADD FOREIGN KEY (BOOK_ID) REFERENCES Books(BOOK_ID);

ALTER TABLE Borrows
	ADD FOREIGN KEY (USER_ID) REFERENCES Users(User_ID);

CREATE TABLE Upgrades(
	UPGRADE_ID INT IDENTITY(1,1) NOT NULL,
	USER_ID INT NOT NULL,
	UPGRADE_REQUESTDATE DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	UPGRADE_RESPONDEDTIME DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	UPGRADE_STATUS INT NOT NULL
);

ALTER TABLE Upgrades
	ADD FOREIGN KEY (USER_ID) REFERENCES Users(User_ID);

INSERT INTO Authors VALUES ('Erich Gamma');
INSERT INTO Authors VALUES ('Eric Freeman');
INSERT INTO Authors VALUES ('Stuart Russell');
INSERT INTO Authors VALUES ('Najwa Zebian');
INSERT INTO Authors VALUES ('Mark Manson');
INSERT INTO Authors VALUES ('George Orwell');
INSERT INTO Authors VALUES ('William Blake');
INSERT INTO Authors VALUES ('Charles Duhigg');

INSERT INTO CATEGORIES VALUES ('Mystery');
INSERT INTO CATEGORIES VALUES ('Science');
INSERT INTO CATEGORIES VALUES ('Biography');
INSERT INTO CATEGORIES VALUES ('Journal');
INSERT INTO CATEGORIES VALUES ('Fantasy');
INSERT INTO CATEGORIES VALUES ('History');
INSERT INTO CATEGORIES VALUES ('Self improvement');
INSERT INTO CATEGORIES VALUES ('Romance');

INSERT INTO USERS VALUES ('baronzemo', 'zemobaron', 'baronzemo@gmail.com', 'Baron Zemo', '1991-12-16T10:00:00', 'Male', '0', NULL);
INSERT INTO USERS VALUES ('mattbellamy', 'bellamymatt', 'mattbellamy@gmail.com', 'Matt Bellamy', '1986-10-10T11:30:30', 'Male', '1', NULL); 

INSERT INTO BORROWS VALUES (13, 1, '2020-04-27T10:00:00', NULL, NULL, 'Pending');
INSERT INTO BORROWS VALUES (30, 1, '2020-04-27T10:00:00', NULL, NULL, 'Pending');

SELECT * FROM BOOKS;

SELECT * FROM AUTHORS;

SELECT * FROM CATEGORIES;

SELECT * FROM USERS;

SELECT * FROM Users WHERE USER_CATEGORY!=0;

ALTER TABLE Books
	ALTER COLUMN BOOK_DESCRIPTION VARCHAR(500);

ALTER TABLE Users
	ALTER COLUMN USER_PASSWORD VARCHAR(100);